/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostRouteImport } from './routes/post'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JudgingRouteImport } from './routes/judging'
import { Route as JudgesRouteImport } from './routes/judges'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmissionBountyIdRouteImport } from './routes/submission.$bountyId'
import { Route as ProfileAddressRouteImport } from './routes/profile.$address'
import { Route as BountyIdRouteImport } from './routes/bounty.$id'
import { Route as BountyIdSubmitRouteImport } from './routes/bounty.$id.submit'

const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgingRoute = JudgingRouteImport.update({
  id: '/judging',
  path: '/judging',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesRoute = JudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionBountyIdRoute = SubmissionBountyIdRouteImport.update({
  id: '/submission/$bountyId',
  path: '/submission/$bountyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAddressRoute = ProfileAddressRouteImport.update({
  id: '/profile/$address',
  path: '/profile/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const BountyIdRoute = BountyIdRouteImport.update({
  id: '/bounty/$id',
  path: '/bounty/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BountyIdSubmitRoute = BountyIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => BountyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/judges': typeof JudgesRoute
  '/judging': typeof JudgingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/post': typeof PostRoute
  '/bounty/$id': typeof BountyIdRouteWithChildren
  '/profile/$address': typeof ProfileAddressRoute
  '/submission/$bountyId': typeof SubmissionBountyIdRoute
  '/bounty/$id/submit': typeof BountyIdSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/judges': typeof JudgesRoute
  '/judging': typeof JudgingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/post': typeof PostRoute
  '/bounty/$id': typeof BountyIdRouteWithChildren
  '/profile/$address': typeof ProfileAddressRoute
  '/submission/$bountyId': typeof SubmissionBountyIdRoute
  '/bounty/$id/submit': typeof BountyIdSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/judges': typeof JudgesRoute
  '/judging': typeof JudgingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/post': typeof PostRoute
  '/bounty/$id': typeof BountyIdRouteWithChildren
  '/profile/$address': typeof ProfileAddressRoute
  '/submission/$bountyId': typeof SubmissionBountyIdRoute
  '/bounty/$id/submit': typeof BountyIdSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/dashboard'
    | '/explore'
    | '/judges'
    | '/judging'
    | '/leaderboard'
    | '/post'
    | '/bounty/$id'
    | '/profile/$address'
    | '/submission/$bountyId'
    | '/bounty/$id/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/dashboard'
    | '/explore'
    | '/judges'
    | '/judging'
    | '/leaderboard'
    | '/post'
    | '/bounty/$id'
    | '/profile/$address'
    | '/submission/$bountyId'
    | '/bounty/$id/submit'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/dashboard'
    | '/explore'
    | '/judges'
    | '/judging'
    | '/leaderboard'
    | '/post'
    | '/bounty/$id'
    | '/profile/$address'
    | '/submission/$bountyId'
    | '/bounty/$id/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  JudgesRoute: typeof JudgesRoute
  JudgingRoute: typeof JudgingRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PostRoute: typeof PostRoute
  BountyIdRoute: typeof BountyIdRouteWithChildren
  ProfileAddressRoute: typeof ProfileAddressRoute
  SubmissionBountyIdRoute: typeof SubmissionBountyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judging': {
      id: '/judging'
      path: '/judging'
      fullPath: '/judging'
      preLoaderRoute: typeof JudgingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges': {
      id: '/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission/$bountyId': {
      id: '/submission/$bountyId'
      path: '/submission/$bountyId'
      fullPath: '/submission/$bountyId'
      preLoaderRoute: typeof SubmissionBountyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$address': {
      id: '/profile/$address'
      path: '/profile/$address'
      fullPath: '/profile/$address'
      preLoaderRoute: typeof ProfileAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounty/$id': {
      id: '/bounty/$id'
      path: '/bounty/$id'
      fullPath: '/bounty/$id'
      preLoaderRoute: typeof BountyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounty/$id/submit': {
      id: '/bounty/$id/submit'
      path: '/submit'
      fullPath: '/bounty/$id/submit'
      preLoaderRoute: typeof BountyIdSubmitRouteImport
      parentRoute: typeof BountyIdRoute
    }
  }
}

interface BountyIdRouteChildren {
  BountyIdSubmitRoute: typeof BountyIdSubmitRoute
}

const BountyIdRouteChildren: BountyIdRouteChildren = {
  BountyIdSubmitRoute: BountyIdSubmitRoute,
}

const BountyIdRouteWithChildren = BountyIdRoute._addFileChildren(
  BountyIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  JudgesRoute: JudgesRoute,
  JudgingRoute: JudgingRoute,
  LeaderboardRoute: LeaderboardRoute,
  PostRoute: PostRoute,
  BountyIdRoute: BountyIdRouteWithChildren,
  ProfileAddressRoute: ProfileAddressRoute,
  SubmissionBountyIdRoute: SubmissionBountyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
